version: '3.5'

services:
  web:
    build:
      context: newsboard
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    command: honcho start
    restart: on-failure:1
    env_file: newsboard/.env
    tty: true
    volumes:
      - ./newsboard/:/code/
    ports:
      - "8000:8000"
    networks:
      - newsboard_net

  db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: "newsboard"
      POSTGRES_DB: "newsboard"
      POSTGRES_PASSWORD: "123"
    # env_file: db/.env   
    networks:
      - newsboard_net

  # redis:
  #   image: "redis:5.0.7-alpine"   
  #   networks:
  #     - newsboard_net    

  # rabbitmq:
  #   build:
  #     context: rabbitmq
  #     dockerfile: Dockerfile
  #   image: rabbitmq:3.8.3-management-alpine
  #   container_name: rabbitmq
  #   env_file: rabbitmq/.env     
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
  #   networks:
  #     - newsboard_net


networks:
  newsboard_net:
    driver: bridge
