# Generated by Django 3.0.6 on 2020-05-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.TextField(max_length=200)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('upvotes', models.IntegerField()),
                ('author', models.TextField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('content', models.TextField(max_length=3000)),
                ('author', models.TextField(max_length=42)),
                ('created_at', models.DateTimeField()),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='main.Post',
                    ),
                ),
            ],
        ),
    ]
